[package]
name = "simd-position"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
